/**
 * EVE Report Verify CLI — Offline PDF Verification
 *
 * Verifies a downloaded PDF against the report vault chain.
 * No server required. No API. Pure local verification.
 *
 * Verification chain:
 *   1. SHA256 of PDF file
 *   2. Lookup in report_vault.jsonl
 *   3. Verify chain integrity (prev_hash → event_hash → chain_hash)
 *   4. Cross-reference dataset_eve_id in dataset vault
 *   5. Display full provenance
 *
 * Usage:
 *   npx tsx packages/evidence/src/ask-eve/verify_report.ts evidence_SE3_202401.pdf
 *
 * Exit 0 = verified. Exit 1 = failed.
 */

import { readFileSync, existsSync } from "fs";
import { createHash } from "crypto";
import { resolve } from "path";

const PROJECT_ROOT = resolve(__dirname, "../../../..");
const REPORT_VAULT = resolve(PROJECT_ROOT, "data", "reports", "report_vault.jsonl");
const DATASET_VAULT = resolve(PROJECT_ROOT, "data", "xvault", "elekto_v2_worm.jsonl");

// ─── Types ───────────────────────────────────────────────────────────────────

interface ReportVaultEntry {
  report_index: number;
  report_hash: string;
  dataset_eve_id: string;
  root_hash: string;
  zone: string;
  period_start: string;
  period_end: string;
  query_command: string;
  created_at_utc: string;
  prev_hash: string | null;
  event_hash: string;
  chain_hash: string;
}

interface DatasetVaultEntry {
  event_index: number;
  event: {
    dataset_eve_id: string;
    root_hash: string;
    methodology_version: string;
    zone: string;
  };
  chain_hash: string;
}

// ─── Main ────────────────────────────────────────────────────────────────────

function main() {
  const pdfPath = process.argv[2];

  if (!pdfPath) {
    console.error("Usage: verify_report.ts <path-to-pdf>");
    console.error("Example: verify_report.ts evidence_SE3_202401.pdf");
    process.exit(1);
  }

  const resolvedPath = resolve(pdfPath);

  console.log("╔══════════════════════════════════════════════════════════════╗");
  console.log("║  EVE Report Verification — Offline                         ║");
  console.log("╚══════════════════════════════════════════════════════════════╝");
  console.log();

  // ─── Step 1: Hash PDF ────────────────────────────────────────────────
  if (!existsSync(resolvedPath)) {
    console.error(`❌ File not found: ${resolvedPath}`);
    process.exit(1);
  }

  const pdfBuffer = readFileSync(resolvedPath);
  const pdfHash = createHash("sha256").update(pdfBuffer).digest("hex");

  console.log(`  📄 File:     ${resolvedPath}`);
  console.log(`  🔑 SHA256:   ${pdfHash}`);
  console.log();

  // ─── Step 2: Lookup in report vault ──────────────────────────────────
  if (!existsSync(REPORT_VAULT)) {
    console.error("❌ Report vault not found: data/reports/report_vault.jsonl");
    process.exit(1);
  }

  const reportLines = readFileSync(REPORT_VAULT, "utf-8").trim().split("\n").filter(Boolean);
  const reportEntries: ReportVaultEntry[] = reportLines.map(l => JSON.parse(l));

  const match = reportEntries.find(e => e.report_hash === pdfHash);

  if (!match) {
    console.log("  ❌ REPORT NOT FOUND IN VAULT");
    console.log();
    console.log("  This PDF hash does not exist in the report vault.");
    console.log("  Possible causes:");
    console.log("    - PDF was modified after generation");
    console.log("    - PDF was not generated by Ask-EVE");
    console.log("    - Report vault is from a different build");
    process.exit(1);
  }

  console.log("  ✅ Report found in vault");
  console.log(`     report_index:   ${match.report_index}`);
  console.log(`     zone:           ${match.zone}`);
  console.log(`     period:         ${match.period_start} → ${match.period_end}`);
  console.log(`     created_at:     ${match.created_at_utc}`);
  console.log(`     dataset_eve_id: ${match.dataset_eve_id}`);
  console.log();

  // ─── Step 3: Verify report vault chain ───────────────────────────────
  let chainValid = true;
  let chainErrors: string[] = [];

  for (let i = 0; i < reportEntries.length; i++) {
    const entry = reportEntries[i];
    if (i === 0) {
      if (entry.prev_hash !== null) {
        chainErrors.push(`Entry ${entry.report_index}: first entry has non-null prev_hash`);
        chainValid = false;
      }
    } else {
      if (entry.prev_hash !== reportEntries[i - 1].chain_hash) {
        chainErrors.push(`Entry ${entry.report_index}: prev_hash mismatch`);
        chainValid = false;
      }
    }
  }

  if (chainValid) {
    console.log(`  ✅ Report vault chain intact (${reportEntries.length} entries)`);
  } else {
    console.log(`  ❌ Report vault chain BROKEN`);
    chainErrors.forEach(e => console.log(`     → ${e}`));
  }
  console.log();

  // ─── Step 4: Cross-reference dataset vault ───────────────────────────
  if (!existsSync(DATASET_VAULT)) {
    console.log("  ⚠️  Dataset vault not found — cannot cross-reference");
  } else {
    const datasetLines = readFileSync(DATASET_VAULT, "utf-8").trim().split("\n").filter(Boolean);
    const datasetEntries: DatasetVaultEntry[] = datasetLines.map(l => JSON.parse(l));

    // Find LAST matching entry (superseding entries come later in chain)
    let datasetMatch: DatasetVaultEntry | undefined;
    for (const e of datasetEntries) {
      if (e.event.dataset_eve_id === match.dataset_eve_id ||
          (e.event as any).supersedes === match.dataset_eve_id) {
        datasetMatch = e;
      }
    }

    if (datasetMatch) {
      const rootMatch = datasetMatch.event.root_hash === match.root_hash;
      console.log(`  ✅ Dataset found in vault`);
      console.log(`     vault_index:    ${datasetMatch.event_index}`);
      console.log(`     root_hash:      ${datasetMatch.event.root_hash.slice(0, 32)}...`);
      console.log(`     root_hash_match: ${rootMatch ? "✅ TRUE" : "❌ FALSE"}`);
      console.log(`     methodology:    ${datasetMatch.event.methodology_version}`);
    } else {
      console.log(`  ❌ Dataset NOT found in vault for ${match.dataset_eve_id}`);
    }
  }
  console.log();

  // ─── Step 5: Rebuild command ─────────────────────────────────────────
  console.log("  📋 Rebuild command:");
  console.log(`     ${match.query_command}`);
  console.log();

  // ─── Summary ─────────────────────────────────────────────────────────
  console.log("════════════════════════════════════════════════════════════════");
  if (chainValid && match) {
    console.log("  🔒 VERIFIED — Report is authentic and chain-linked");
  } else {
    console.log("  ❌ VERIFICATION FAILED");
    process.exit(1);
  }
  console.log("════════════════════════════════════════════════════════════════");
}

main();
